### ISSUE TITLE
Handle CustomEvents

### ISSUE THREAD

**Issue by Triipaxx** [gohilla/universal_html#4]
Hey guys,

is it somehow possible to handle JS CustomEvents with your library?
I'm working on a web app using Flutter 1.9+ which is embedding a OpenLayers map using IFrameElement. I've added an event listener which is properly called when the CustomEvent is dispatched. My problem now is, that the listener takes in an object of the type Event but i need a CustomEvent to access detail data. I've already tried to cast the passed in object to CustomEvent which always fails.

Is there any chance to get this working?

**Comment by terrier989** [comment]
Hi! It sounds like the issue occurs in the browser (dart:html)? In that case, this package can't provide any help.
